### PR TITLE
add more links to learn coding

### PR DESCRIPTION
**Pull request by t42huang**
@hector12free plz review, thx!

### CODE REVIEW

**Review by hector12free — CHANGES_REQUESTED** [review]
plz fix the format. thx!

**Review by hector12free — COMMENTED** [review]
look cool! but could you change it to bullet points instead of numbering? The numbering doesn't mean anything here, right?

😃I'm just being picky here, you don't have to make changes if you don't want to. LOL

**Comment by t42huang** [comment]
> look cool! but could you change it to bullet points instead of numbering? The numbering doesn't mean anything here, right?
> 
> 😃I'm just being picky here, you don't have to make changes if you don't want to. LOL

thx for your suggestion, that's cool. Could you review it again? thx!

**Review by hector12free — APPROVED** [review]
great, I will approve, thx!

**Pull request merged**
